In [12]:
!wget https://s3.amazonaws.com/video.udacity-data.com/topher/2019/January/5c4147f9_data/data.zip
!unzip data


--2021-03-03 12:35:35--  https://s3.amazonaws.com/video.udacity-data.com/topher/2019/January/5c4147f9_data/data.zip
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.24.214
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.24.214|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 113826 (111K) [application/zip]
Saving to: ‘data.zip.2’

data.zip.2          100%[===================>] 111.16K   391KB/s    in 0.3s    

2021-03-03 12:35:35 (391 KB/s) - ‘data.zip.2’ saved [113826/113826]

Archive:  data.zip
replace data/.DS_Store? [y]es, [n]o, [A]ll, [N]one, [r]ename: ^C


In [95]:
# import libraries
import pandas as pd
import numpy as np
import os

In [96]:
csv_file = 'data/file_information.csv'
plagiarism_df = pd.read_csv(csv_file)

# print out the first few rows of data info
plagiarism_df.head()

File Task Category
0  g0pA_taska.txt    a      non
1  g0pA_taskb.txt    b      cut
2  g0pA_taskc.txt    c    light
3  g0pA_taskd.txt    d    heavy
4  g0pA_taske.txt    e      non

In [97]:

def con_num(x):
    if x == 'non':
        return 0
    elif x == 'heavy':
        return 1
    elif x == 'light':
        return 2
    elif x == 'cut':
        return 3
    elif x == 'orig':
        return -1


In [98]:

def add_class(row):
    if row['Category']==0:
        return 0
    elif row['Category']==-1:
        return -1
    else:
        return 1


In [99]:
# Read in a csv file and return a transformed dataframe

def numerical_dataframe(csv_file='data/file_information.csv'):
    '''Reads in a csv file which is assumed to have `File`, `Category` and `Task` columns.
       This function does two things: 
       1) converts `Category` column values to numerical values 
       2) Adds a new, numerical `Class` label column.
       The `Class` column will label plagiarized answers as 1 and non-plagiarized as 0.
       Source texts have a special label, -1.
       :param csv_file: The directory for the file_information.csv file
       :return: A dataframe with numerical categories and a new `Class` label column'''
    
    # your code here
    plagiarism_df = pd.read_csv(csv_file)
    plagiarism_df['Category']=plagiarism_df['Category'].apply(con_num)
    plagiarism_df['Class'] = plagiarism_df.apply (lambda row: add_class(row), axis=1)
    
    
    return plagiarism_df


In [100]:
# informal testing, print out the results of a called function
# create new `transformed_df`
transformed_df = numerical_dataframe(csv_file ='data/file_information.csv')

# check work
# check that all categories of plagiarism have a class label = 1
transformed_df.head(10)

File Task  Category  Class
0  g0pA_taska.txt    a         0      0
1  g0pA_taskb.txt    b         3      1
2  g0pA_taskc.txt    c         2      1
3  g0pA_taskd.txt    d         1      1
4  g0pA_taske.txt    e         0      0
5  g0pB_taska.txt    a         0      0
6  g0pB_taskb.txt    b         0      0
7  g0pB_taskc.txt    c         3      1
8  g0pB_taskd.txt    d         2      1
9  g0pB_taske.txt    e         1      1

In [101]:
import ph

In [102]:
# test cell that creates `transformed_df`, if tests are passed

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""

# importing tests
import problem_unittests as tests

# test numerical_dataframe function
tests.test_numerical_df(numerical_dataframe)

# if above test is passed, create NEW `transformed_df`
transformed_df = numerical_dataframe(csv_file ='data/file_information.csv')

# check work
print('\nExample data: ')
transformed_df.head()

Tests Passed!

Example data: 


File Task  Category  Class
0  g0pA_taska.txt    a         0      0
1  g0pA_taskb.txt    b         3      1
2  g0pA_taskc.txt    c         2      1
3  g0pA_taskd.txt    d         1      1
4  g0pA_taske.txt    e         0      0

In [103]:
"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
import helpers 

# create a text column 
text_df = helpers.create_text_column(transformed_df)
text_df.head()

File Task  Category  Class  \
0  g0pA_taska.txt    a         0      0   
1  g0pA_taskb.txt    b         3      1   
2  g0pA_taskc.txt    c         2      1   
3  g0pA_taskd.txt    d         1      1   
4  g0pA_taske.txt    e         0      0   

                                                Text  
0  inheritance is a basic concept of object orien...  
1  pagerank is a link analysis algorithm used by ...  
2  the vector space model also called term vector...  
3  bayes theorem was names after rev thomas bayes...  
4  dynamic programming is an algorithm design tec...

In [104]:
# after running the cell above
# check out the processed text for a single file, by row index
row_idx = 5 # feel free to change this index

sample_text = text_df.iloc[55]['Text']

print('Sample processed text:\n\n', sample_text)

Sample processed text:

 when we talk about inheritance in object oriented programming languages which is a concept that was invented in 1967 for simula we are usually talking about a way to form new classes and classes are instances of which are called objects and involve using classes that have already been defined  derived classes are intended to help reuse existing code with little or no modification and are the new classes that take over or inherit attributes and behavior of the pre existing classes usually referred to as base classes or ancestor classes  categorization in computer languages is a powerful way number of processing information and inheritance provides the support for representation by categorization furthermore  it is fundamental for helping humans learn by means of generalization in what is known about specific entities is applied to a wider group given a belongs relation can be established and cognitive processing which involves less information being acquired to 

In [105]:
random_seed = 1 # can change; set for reproducibility

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
import helpers

# create new df with Datatype (train, test, orig) column
# pass in `text_df` from above to create a complete dataframe, with all the information you need
complete_df = helpers.train_test_dataframe(text_df, random_seed=random_seed)

# check results
complete_df.head(10)

File Task  Category  Class  \
0  g0pA_taska.txt    a         0      0   
1  g0pA_taskb.txt    b         3      1   
2  g0pA_taskc.txt    c         2      1   
3  g0pA_taskd.txt    d         1      1   
4  g0pA_taske.txt    e         0      0   
5  g0pB_taska.txt    a         0      0   
6  g0pB_taskb.txt    b         0      0   
7  g0pB_taskc.txt    c         3      1   
8  g0pB_taskd.txt    d         2      1   
9  g0pB_taske.txt    e         1      1   

                                                Text Datatype  
0  inheritance is a basic concept of object orien...    train  
1  pagerank is a link analysis algorithm used by ...     test  
2  the vector space model also called term vector...    train  
3  bayes theorem was names after rev thomas bayes...    train  
4  dynamic programming is an algorithm design tec...    train  
5  inheritance is a basic concept in object orien...    train  
6  pagerank pr refers to both the concept and the...    train  
7  vector space model is an algebraic model for r...     test  
8  bayes theorem relates the conditional and marg...    train  
9  dynamic programming is a method for solving ma...     test

In [106]:
sample_text = complete_df.iloc[0]['Text']
print(sample_text)

inheritance is a basic concept of object oriented programming where the basic idea is to create new classes that add extra detail to existing classes this is done by allowing the new classes to reuse the methods and variables of the existing classes and new methods and classes are added to specialise the new class inheritance models the is kind of relationship between entities or objects  for example postgraduates and undergraduates are both kinds of student this kind of relationship can be visualised as a tree structure where student would be the more general root node and both postgraduate and undergraduate would be more specialised extensions of the student node or the child nodes  in this relationship student would be known as the superclass or parent class whereas  postgraduate would be known as the subclass or child class because the postgraduate class extends the student class  inheritance can occur on several layers where if visualised would display a larger tree structure for 

In [107]:

category_vals.append(complete_df.loc[i, 'Category'])
# calculate containment for given file and n
filename = complete_df.loc[1, 'File']
#c = calculate_containment(complete_df, n, filename)
#containment_vals.append(c)
s=pd.read_csv(filename)


NameError: name 'category_vals' is not defined

In [108]:
from sklearn.feature_extraction.text import CountVectorizer
def cal_CountVect(n,a_text,s_text):
    counts_2grams = CountVectorizer(analyzer='word', ngram_range=(n,n))
    bigram_counts = counts_2grams.fit_transform([a_text, s_text])
    bigram_array=(bigram_counts.toarray())
    list_feature=counts_2grams.get_feature_names()
    '''
    list_len_atext=[]
    a_text=a_text.lower()
    for i in list_feature:
        if i in a_text:
            list_len_atext.append(i)

    len_list_len_atext=len(list_len_atext)
    
    x=(bigram_counts.toarray())
    count=0
    for i in range(len(x[0])):
        if x[0][i]==x[1][i]:
           count+=1 
        
    return count/len_list_len_atext
    '''
    ngram_array=bigram_array
    intersection = [min(a, s) for a, s in zip(*ngram_array)]
    c_value = sum(intersection) / sum(ngram_array[0])

    return c_value

In [109]:
df=complete_df
#answer_df = df.query('File == @answer_filename')
#a_text = answer_df.iloc[0].at['Text']
source_filename = 'orig_task'+answer_filename[9]+'.txt'
source_df = df.query('File == @source_filename')
s_text = source_df.iloc[0].at['Text']
print(s_text)
    # your code here

NameError: name 'answer_filename' is not defined

In [110]:
# Calculate the ngram containment for one answer file/source file pair in a df
def calculate_containment(df, n, answer_filename):
    '''Calculates the containment between a given answer text and its associated source text.
       This function creates a count of ngrams (of a size, n) for each text file in our data.
       Then calculates the containment by finding the ngram count for a given answer text, 
       and its associated source text, and calculating the normalized intersection of those counts.
       :param df: A dataframe with columns,
           'File', 'Task', 'Category', 'Class', 'Text', and 'Datatype'
       :param n: An integer that defines the ngram size
       :param answer_filename: A filename for an answer text in the df, ex. 'g0pB_taskd.txt'
       :return: A single containment value that represents the similarity
           between an answer text and its source text.
    '''
    answer_df = df.query('File == @answer_filename')
    a_text = answer_df.iloc[0].at['Text']
    source_filename = 'orig_task'+answer_filename[9]+'.txt'
    source_df = df.query('File == @source_filename')
    s_text = source_df.iloc[0].at['Text']
    
    # your code here
    #for i in range(len(df)):
    #   sample_text = df.iloc[i]['Text']
    #   filename =answer_text
    print()
    return cal_CountVect(n,a_text,s_text)
   
        

In [111]:
#answer_filename="inheritance is a basic concept of object oriented programming where the basic idea is to create new classes that add extra detail to existing classes this is done by allowing the new classes to reuse the methods and variables of the existing classes and new methods and classes are added to specialise the new class inheritance models the is kind of relationship between entities or objects  for example postgraduates and undergraduates are both kinds of student this kind of relationship can be visualised as a tree structure where student would be the more general root node and both postgraduate and undergraduate would be more specialised extensions of the student node or the child nodes  in this relationship student would be known as the superclass or parent class whereas  postgraduate would be known as the subclass or child class because the postgraduate class extends the student class  inheritance can occur on several layers where if visualised would display a larger tree structure for example we could further extend the postgraduate node by adding two extra extended classes to it called  msc student and phd student as both these types of student are kinds of postgraduate student this would mean that both the msc student and phd student classes would inherit methods and variables from both the postgraduate and student classes"  



In [112]:
# select a value for n
n = 3

# indices for first few files
test_indices = range(5)

# iterate through files and calculate containment
category_vals = []
containment_vals = []
for i in test_indices:
    # get level of plagiarism for a given file index
    category_vals.append(complete_df.loc[i, 'Category'])
    # calculate containment for given file and n
    filename = complete_df.loc[i, 'File']
    c = calculate_containment(complete_df, n, filename)
    containment_vals.append(c)

# print out result, does it make sense?
print('Original category values: \n', category_vals)
print()
print(str(n)+'-gram containment values: \n', containment_vals)






Original category values: 
 [0, 3, 2, 1, 0]

3-gram containment values: 
 [0.009345794392523364, 0.9641025641025641, 0.6136363636363636, 0.15675675675675677, 0.031746031746031744]


In [113]:
# run this test cell
"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
# test containment calculation
# params: complete_df from before, and containment function
tests.test_containment(complete_df, calculate_containment)










Tests Passed!


In [114]:

# Compute the normalized LCS given an answer text and a source text
def lcs_norm_word(answer_text, source_text):
    '''Computes the longest common subsequence of words in two texts; returns a normalized value.
       :param answer_text: The pre-processed text for an answer text
       :param source_text: The pre-processed text for an answer's associated source text
       :return: A normalized LCS value'''
    
    answer_text=answer_text.split()
    source_text=source_text.split()
    answer_size = len(answer_text)
    source_size = len(source_text)

    #main cases.
    #if no word retturn 0
    if answer_size == 0 or source_size == 0:
        return 0
    #if one word and similar return 1 
    if answer_size == 1 and source_size == 1:
        if answer_text[0] == source_text[0]:
            return 1
        else:
            return 0

    # Making a matrix to store the elemwnt inside it.
    martrix_2d = [[0 for i in range(source_size + 1)] for j in range(answer_size + 1)]

    for i in range(1, answer_size + 1):
        for j in range(1, source_size + 1):
            if answer_text[i - 1] == source_text[j - 1]: #if match 
                martrix_2d[i][j] = 1 + martrix_2d[i - 1][j - 1] #1+ value from last word in answer and last word from source

            else:
                martrix_2d[i][j] = max(martrix_2d[i][j - 1], martrix_2d[i - 1][j]) #if miss match

    last_element= martrix_2d[-1][-1]
    LCS_value=last_element/answer_size
    return LCS_value

In [115]:
answer_text="i think pagerank is a link analysis algorithm used by google that uses a system of weights attached to each element of a hyperlinked set of documents"
source_text="pagerank is a link analysis algorithm used by the google internet search engine that assigns a numerical weighting to each element of a hyperlinked set of documents"




print("Length of LCS is ", lcs_norm_word(answer_text, source_text))

Length of LCS is  0.7407407407407407


In [116]:

# Run the test scenario from above
# does your function return the expected value?

A = "i think pagerank is a link analysis algorithm used by google that uses a system of weights attached to each element of a hyperlinked set of documents"
S = "pagerank is a link analysis algorithm used by the google internet search engine that assigns a numerical weighting to each element of a hyperlinked set of documents"

# calculate LCS
lcs = lcs_norm_word(A, S)
print('LCS = ', lcs)


# expected value test
assert lcs==20/27, "Incorrect LCS value, expected about 0.7408, got "+str(lcs)

print('Test passed!')

LCS =  0.7407407407407407
Test passed!


In [117]:
# run test cell
"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
# test lcs implementation
# params: complete_df from before, and lcs_norm_word function
tests.test_lcs(complete_df, lcs_norm_word)

Tests Passed!


In [118]:

# test on your own
test_indices = range(5) # look at first few files

category_vals = []
lcs_norm_vals = []
# iterate through first few docs and calculate LCS
for i in test_indices:
    category_vals.append(complete_df.loc[i, 'Category'])
    # get texts to compare
    answer_text = complete_df.loc[i, 'Text'] 
    task = complete_df.loc[i, 'Task']
    # we know that source texts have Class = -1
    orig_rows = complete_df[(complete_df['Class'] == -1)]
    orig_row = orig_rows[(orig_rows['Task'] == task)]
    source_text = orig_row['Text'].values[0]
    
    # calculate lcs
    lcs_val = lcs_norm_word(answer_text, source_text)
    lcs_norm_vals.append(lcs_val)

# print out result, does it make sense?
print('Original category values: \n', category_vals)
print()
print('Normalized LCS values: \n', lcs_norm_vals)

Original category values: 
 [0, 3, 2, 1, 0]

Normalized LCS values: 
 [0.1917808219178082, 0.8207547169811321, 0.8464912280701754, 0.3160621761658031, 0.24257425742574257]


In [124]:

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
# Function returns a list of containment features, calculated for a given n 
# Should return a list of length 100 for all files in a complete_df
def create_containment_features(df, n, column_name=None):
    
    containment_values = []
    
    if(column_name==None):
        column_name = 'c_'+str(n) # c_1, c_2, .. c_n
    
    # iterates through dataframe rows
    for i in df.index:
        file = df.loc[i, 'File']
        # Computes features using calculate_containment function
        if df.loc[i,'Category'] > -1:
            c = calculate_containment(df, n, file)
            containment_values.append(c)
        # Sets value to -1 for original tasks 
        else:
            containment_values.append(-1)
    
    print(str(n)+'-gram containment features created!')
    return containment_values

In [125]:

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
# Function creates lcs feature and add it to the dataframe
def create_lcs_features(df, column_name='lcs_word'):
    
    lcs_values = []
    
    # iterate through files in dataframe
    for i in df.index:
        # Computes LCS_norm words feature using function above for answer tasks
        if df.loc[i,'Category'] > -1:
            # get texts to compare
            answer_text = df.loc[i, 'Text'] 
            task = df.loc[i, 'Task']
            # we know that source texts have Class = -1
            orig_rows = df[(df['Class'] == -1)]
            orig_row = orig_rows[(orig_rows['Task'] == task)]
            source_text = orig_row['Text'].values[0]

            # calculate lcs
            lcs = lcs_norm_word(answer_text, source_text)
            lcs_values.append(lcs)
        # Sets to -1 for original tasks 
        else:
            lcs_values.append(-1)

    print('LCS features created!')
    return lcs_values

In [130]:
# Define an ngram range
ngram_range = range(1,6)


# The following code may take a minute to run, depending on your ngram_range
"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
features_list = []

# Create features in a features_df
all_features = np.zeros((len(ngram_range)+1, len(complete_df)))

# Calculate features for containment for ngrams in range
i=0
for n in ngram_range:
    column_name = 'c_'+str(n)
    features_list.append(column_name)
    # create containment features
    all_features[i]=np.squeeze(create_containment_features(complete_df, n))
    i+=1

# Calculate features for LCS_Norm Words 
features_list.append('lcs_word')
all_features[i]= np.squeeze(create_lcs_features(complete_df))

# create a features dataframe
features_df = pd.DataFrame(np.transpose(all_features), columns=features_list)

# Print all features/columns
print()
print('Features: ', features_list)
print()
































































































1-gram containment features created!































































































2-gram containment features created!































































































3-gram containment features created!































































































4-gram containment features created!































































































5-gram containment features created!
LCS features created!

Features:  ['c_1', 'c_2', 'c_3', 'c_4', 'c_5', 'lcs_word']



In [131]:
features_df.head(10)

c_1       c_2       c_3       c_4       c_5  lcs_word
0  0.398148  0.079070  0.009346  0.000000  0.000000  0.191781
1  1.000000  0.984694  0.964103  0.943299  0.922280  0.820755
2  0.869369  0.719457  0.613636  0.515982  0.449541  0.846491
3  0.593583  0.268817  0.156757  0.108696  0.081967  0.316062
4  0.544503  0.115789  0.031746  0.005319  0.000000  0.242574
5  0.329502  0.053846  0.007722  0.003876  0.000000  0.161172
6  0.590308  0.150442  0.035556  0.004464  0.000000  0.301653
7  0.765306  0.709898  0.664384  0.625430  0.589655  0.621711
8  0.759777  0.505618  0.395480  0.306818  0.245714  0.484305
9  0.884444  0.526786  0.340807  0.247748  0.180995  0.597458

In [132]:

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
# Create correlation matrix for just Features to determine different models to test
corr_matrix = features_df.corr().abs().round(2)

# display shows all of a dataframe
display(corr_matrix)

c_1   c_2   c_3   c_4   c_5  lcs_word
c_1       1.00  0.94  0.90  0.89  0.88      0.97
c_2       0.94  1.00  0.99  0.98  0.97      0.98
c_3       0.90  0.99  1.00  1.00  0.99      0.97
c_4       0.89  0.98  1.00  1.00  1.00      0.95
c_5       0.88  0.97  0.99  1.00  1.00      0.95
lcs_word  0.97  0.98  0.97  0.95  0.95      1.00

In [189]:
complete_df

File Task  Category  Class  \
0   g0pA_taska.txt    a         0      0   
1   g0pA_taskb.txt    b         3      1   
2   g0pA_taskc.txt    c         2      1   
3   g0pA_taskd.txt    d         1      1   
4   g0pA_taske.txt    e         0      0   
..             ...  ...       ...    ...   
95  orig_taska.txt    a        -1     -1   
96  orig_taskb.txt    b        -1     -1   
97  orig_taskc.txt    c        -1     -1   
98  orig_taskd.txt    d        -1     -1   
99  orig_taske.txt    e        -1     -1   

                                                 Text Datatype  
0   inheritance is a basic concept of object orien...    train  
1   pagerank is a link analysis algorithm used by ...     test  
2   the vector space model also called term vector...    train  
3   bayes theorem was names after rev thomas bayes...    train  
4   dynamic programming is an algorithm design tec...    train  
..                                                ...      ...  
95  in object oriented programming inheritance is ...     orig  
96  pagerank is a link analysis algorithm used by ...     orig  
97  vector space model or term vector model is an ...     orig  
98  in probability theory bayes theorem often call...     orig  
99  in mathematics and computer science dynamic pr...     orig  

[100 rows x 6 columns]

In [195]:
complete_df.loc[complete_df['Datatype']=='train',['Class']].tail(10)

Class
79      1
82      0
85      1
86      1
88      0
89      1
90      1
91      1
92      1
93      0

In [196]:
complete_df.loc[complete_df['Datatype']=='test',['Class']].tail(10)

Class
61      1
62      1
63      1
75      0
80      1
81      0
83      1
84      1
87      0
94      0

In [184]:
complete_df_train=complete_df[complete_df['Datatype']=='train']
complete_df_train_class=complete_df_train[['Class']]
complete_df_train_class.index()

TypeError: 'Int64Index' object is not callable

In [207]:
x=features_df[['c_2','lcs_word']].loc[[1,7,9,10,16,20,23,25,29,31,37,38,47,48,49,61,62,63,75,80,81,83,84,87,94]]
import numpy as np
ft2=np.array(x)
ft2

array([[0.98469388, 0.82075472],
       [0.70989761, 0.62171053],
       [0.52678571, 0.59745763],
       [0.25      , 0.42783505],
       [0.67567568, 0.775     ],
       [0.98529412, 0.99305556],
       [0.11290323, 0.34666667],
       [0.07      , 0.18932039],
       [0.14210526, 0.24742268],
       [0.14285714, 0.29441624],
       [0.15178571, 0.25833333],
       [0.17164179, 0.27891156],
       [0.2513089 , 0.34158416],
       [0.84279476, 0.92941176],
       [0.98084291, 1.        ],
       [0.39690722, 0.50471698],
       [0.465625  , 0.55855856],
       [0.99230769, 0.99669967],
       [0.07614213, 0.17874396],
       [0.98905109, 0.85467128],
       [0.13375796, 0.29834254],
       [0.9375    , 0.92708333],
       [0.86721992, 0.90980392],
       [0.10212766, 0.17741935],
       [0.1637931 , 0.24583333]])

In [215]:
#Takes in dataframes and a list of selected features (column names) 
# and returns (train_x, train_y), (test_x, test_y)
def train_test_data(complete_df, features_df, selected_features):
    '''Gets selected training and test features from given dataframes, and 
       returns tuples for training and test features and their corresponding class labels.
       :param complete_df: A dataframe with all of our processed text data, datatypes, and labels
       :param features_df: A dataframe of all computed, similarity features
       :param selected_features: An array of selected features that correspond to certain columns in `features_df`
       :return: training and test features and labels: (train_x, train_y), (test_x, test_y)'''
    
    
    complete_df_train=complete_df[complete_df['Datatype']=='train']
    complete_df_train_class=complete_df_train[['Class']]
    
    complete_df_test=complete_df[complete_df['Datatype']=='test']
    complete_df_test_class=complete_df_test[['Class']]
    
    # get the training features
    train_x_data =features_df[selected_features].loc[[0, 2, 3, 4, 5, 6, 8, 11, 12, 13, 14, 15, 17, 18, 19, 21, 22, 24, 26, 27, 28, 30, 32, 33, 34, 35, 36, 39, 40, 41, 42, 43, 44, 45, 46, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 76, 77, 78, 79, 82, 85, 86, 88, 89, 90, 91, 92, 93]]
    train_x=np.array(train_x_data)
    
    # And training class labels (0 or 1)
    train_y_data = complete_df.loc[complete_df['Datatype']=='train','Class']
    train_y=np.array(train_y_data)
    
    # get the test features and labels
    
    test_x_data= features_df[selected_features].loc[[1,7,9,10,16,20,23,25,29,31,37,38,47,48,49,61,62,63,75,80,81,83,84,87,94]]
    test_x=np.array(test_x_data)
    
    test_y_data = complete_df.loc[complete_df['Datatype']=='test','Class']
    test_y=np.array(test_y_data)
    
    return (train_x, train_y), (test_x, test_y)

In [216]:

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
test_selection = list(features_df)[:2] # first couple columns as a test
# test that the correct train/test data is created
(train_x, train_y), (test_x, test_y) = train_test_data(complete_df, features_df, test_selection)

# params: generated train/test data
tests.test_data_split(train_x, train_y, test_x, test_y)

Tests Passed!


In [218]:

# Select your list of features, this should be column names from features_df
# ex. ['c_1', 'lcs_word']
selected_features = ['c_1', 'c_5', 'lcs_word']
#selected_features = ['c_2','lcs_word']


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""

(train_x, train_y), (test_x, test_y) = train_test_data(complete_df, features_df, selected_features)

# check that division of samples seems correct
# these should add up to 95 (100 - 5 original files)
print('Training size: ', len(train_x))
print('Test size: ', len(test_x))
print()
print('Training df sample: \n', train_x[:10])

Training size:  70
Test size:  25

Training df sample: 
 [[0.39814815 0.         0.19178082]
 [0.86936937 0.44954128 0.84649123]
 [0.59358289 0.08196721 0.31606218]
 [0.54450262 0.         0.24257426]
 [0.32950192 0.         0.16117216]
 [0.59030837 0.         0.30165289]
 [0.75977654 0.24571429 0.48430493]
 [0.51612903 0.         0.27083333]
 [0.44086022 0.         0.22395833]
 [0.97945205 0.78873239 0.9       ]]


In [255]:

def make_csv(x, y, filename, data_dir):
    '''Merges features and labels and converts them into one csv file with labels in the first column.
       :param x: Data features
       :param y: Data labels
       :param file_name: Name of csv file, ex. 'train.csv'
       :param data_dir: The directory where files will be saved
       '''
    # make data dir, if it does not exist
    if not os.path.exists(data_dir):
        os.makedirs(data_dir)
    
    
    # your code here
    x=pd.DataFrame(x)
    y=pd.DataFrame(y)
    #x['Class']=(y)
    
    pd.concat([y,x],axis=1).to_csv(os.path.join(data_dir, filename), header=False, index=False)
    
    # nothing is returned, but a print statement indicates that the function has run
    print('Path created: '+str(data_dir)+'/'+str(filename))

In [256]:
"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
fake_x = [ [0.39814815, 0.0001, 0.19178082], 
           [0.86936937, 0.44954128, 0.84649123], 
           [0.44086022, 0., 0.22395833] ]

fake_y = [0, 1, 1]

make_csv(fake_x, fake_y, filename='to_delete.csv', data_dir='test_csv')

# read in and test dimensions
fake_df = pd.read_csv('test_csv/to_delete.csv', header=None)

# check shape
assert fake_df.shape==(3, 4), \
      'The file should have as many rows as data_points and as many columns as features+1 (for indices).'
# check that first column = labels
assert np.all(fake_df.iloc[:,0].values==fake_y), 'First column is not equal to the labels, fake_y.'
print('Tests passed!')

Path created: test_csv/to_delete.csv
Tests passed!


In [257]:
# delete the test csv file, generated above
! rm -rf test_csv

In [258]:
# can change directory, if you want
data_dir = 'plagiarism_data'

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""

make_csv(train_x, train_y, filename='train.csv', data_dir=data_dir)
make_csv(test_x, test_y, filename='test.csv', data_dir=data_dir)

Path created: plagiarism_data/train.csv
Path created: plagiarism_data/test.csv


In [ ]:
# session and role
sagemaker_session = sagemaker.Session()
role = sagemaker.get_execution_role()

# create an S3 bucket
bucket = sagemaker_session.default_bucket()

In [ ]:

# should be the name of directory you created to save your features data
data_dir = None

# set prefix, a descriptive name for a directory  
prefix = sagemaker_session

# upload all data to S3